-- 1
SELECT DEPARTMENT_NAME as "학과 명", CATEGORY as "계열" FROM TB_DEPARTMENT;

-- 2
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.' 
FROM TB_DEPARTMENT;

-- 3
SELECT DEPARTMENT_NO, DEPARTMENT_NAME
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '국어국문학과';

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y' and DEPARTMENT_NO='001' and STUDENT_SSN LIKE '_______2%';

-- 4
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ( 'A513079', 'A513090', 'A513091', 'A513110', 'A513119' )
ORDER BY STUDENT_NO DESC;

-- 5
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE 20<=CAPACITY and CAPACITY <=30;

-- 6
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

-- 10
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N' and STUDENT_NO LIKE 'A2%' and STUDENT_ADDRESS LIKE '전주%'
ORDER BY STUDENT_NAME;
