-- 1
SELECT COUNT(*) "학생 수"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '003'
GROUP BY ENTRANCE_DATE
HAVING TO_CHAR(ENTRANCE_DATE, 'YY')='01';

SELECT *
FROM TB_DEPARTMENT;

--2
SELECT CATEGORY 계열, DEPARTMENT_NAME 학과이름, CAPACITY 정원
FROM TB_DEPARTMENT
WHERE CATEGORY = '공학' AND CAPACITY >= 20 AND CAPACITY <= 30
ORDEr BY CAPACITY;

--3
SELECT CATEGORY 계열, COUNT(DEPARTMENT_NO) 학과수
FROM TB_DEPARTMENT
WHERE CATEGORY LIKE '%학%'
GROUP BY CATEGORY
ORDER BY 학과수 DESC;

--4
SELECT PROFESSOR_NAME 교수이름, SUBSTR(PROFESSOR_SSN, 1, 2) 출생년도, PROFESSOR_ADDRESS 주소
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '002'
ORDER BY 출생년도;

SELECT *
FROM TB_DEPARTMENT;

--5 
SELECT DEPARTMENT_NO, STUDENT_NAME, DECODE(ABSENCE_YN, 'Y', '정상', 'N', '휴학')
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001' AND STUDENT_ADDRESS LIKE '%서울%';

SELECT *
FROM TB_STUDENT;