-- 1번
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE; 

-- 2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3번
SELECT PROFESSOR_NAME 교수이름, 22 + (100 - SUBSTR(PROFESSOR_SSN, 1, 2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 나이;

-- 4번
SELECT SUBSTR(PROFESSOR_NAME, 2, 3) 교수이름
FROM TB_PROFESSOR;

-- 5번 ??????? 119살 어쩔...
SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE, SUBSTR(STUDENT_SSN, 1, 2), 100-SUBSTR(STUDENT_SSN, 1, 2)+TO_CHAR(ENTRANCE_DATE, 'YY') TSET
FROM TB_STUDENT
WHERE 100-SUBSTR(STUDENT_SSN, 1, 2)+TO_CHAR(ENTRANCE_DATE, 'YY') > 19;

-- 6번 어쩔티비
SELECT NEXT_DAY('20/12/19', '금')
FROM dual;
-- 정답 : 금요일

-- 8번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1, 1) != 'A';

-- 9번
SELECT AVG(
FROM TB_GRADE
GROUP BY STUDENT_NO = 'A517178';
