-- 1번
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE; 

-- 2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3번
SELECT PROFESSOR_NAME 교수이름, 22 + (100 - SUBSTR(PROFESSOR_SSN, 1, 2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 나이;

-- 4번
SELECT SUBSTR(PROFESSOR_NAME, 2, 3) 교수이름
FROM TB_PROFESSOR;

-- 5번 ??????? 119살 어쩔...
SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE, SUBSTR(STUDENT_SSN, 1, 2), 100-SUBSTR(STUDENT_SSN, 1, 2)+TO_CHAR(ENTRANCE_DATE, 'YY') TSET
FROM TB_STUDENT
WHERE 100-SUBSTR(STUDENT_SSN, 1, 2)+TO_CHAR(ENTRANCE_DATE, 'YY') > 19;

-- 6번 어쩔티비
SELECT NEXT_DAY('20/12/19', '금')
FROM dual;
-- 정답 : 금요일

-- 8번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1, 1) != 'A';

-- 9
SELECT ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178'
GROUP BY STUDENT_NO;

-- 10
SELECT DEPARTMENT_NO 학과번호, CAPACITY "학생수(명)"
FROM TB_DEPARTMENT;

-- 11
SELECT COUNT(*) as "COUNT(*)"
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL
GROUP BY COACH_PROFESSOR_NO;

-- 12
SELECT SUBSTR(TERM_NO, 1, 4) 년도, ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 년도;

-- 13
SELECT COUNT(ABSENCE_YN)
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO;

-- 14
SELECT STUDENT_NAME 동일이름, COUNT(STUDENT_NAME) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) > 1;

