-- 6
SELECT RPAD(SUBSTR(STUDENT_SSN, 1, 8), 14, '*') 주민번호, STUDENT_NAME 이름
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_SSN, 1, 2) = '80' AND STUDENT_NAME LIKE '김%' AND SUBSTR(STUDENT_SSN, 8, 1) = '2';

--7
SELECT DEPARTMENT_NAME 학과이름, CAPACITY 현재정원, 
CASE WHEN CAPACITY >= 40 THEN '대강의실' 
        WHEN CAPACITY >= 30 THEN '중강의실' 
        ELSE '소강의실' END AS 강의실크기
FROM TB_DEPARTMENT
WHERE CATEGORY = '예체능';

SELECT *
FROM TB_DEPARTMENT
WHERE CAPACITY >= 20;

--8
SELECT DEPARTMENT_NO, STUDENT_NAME, COACH_PROFESSOR_NO, TO_CHAR(ENTRANCE_DATE, 'YYYY')
FROM TB_STUDENT
WHERE STUDENT_ADDRESS IS NULL AND (TO_CHAR(ENTRANCE_DATE, 'YY')='06' OR TO_CHAR(ENTRANCE_DATE, 'YY')='05') 
ORDER BY ENTRANCE_DATE;
